### ISSUE TITLE
Server boot crash issue with Moreboots-1.1.0-1.16.x on Forge 35.1.1 (Minecraft 1.16.4)

### ISSUE THREAD

**Issue by solarblindfull** [North-West-Wind/MoreBoots#1]
Hello ! Thank very much for all this very funny and colorfull boots !

I'm on a minecraft forge 35.1.1 server (1.16.4) and my server have a boot crash issue with your mod (moreboots-1.1.0-1.16.x version) as you can see in my lastest server log below.

<details>
<summary>Lastest server log</summary>

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [

	More Boots (moreboots) encountered an error during the load_registries event phase

java.lang.NoSuchMethodError: net.minecraft.block.SkullBlock.func_196292_N_()Lnet/minecraft/block/SkullBlock$ISkullType;

]

	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?]

	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?]

	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?]

	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]

	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]

	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.1.jar:35.1]

	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]

	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.1.jar:?]

	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.1.jar:?]

	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.1.jar:?]

</details>

Can you see what's wrong please ?
Thank for your attention.

Have a very good day !

**Comment by North-West-Wind** [comment]
Is this the entire log? If so, that may take some time for me to figure it out.

Also, I don't know if that's a typo or not, but a Minecraft Forge 31.1.1 server should be a 1.15.2 server???

**Comment by solarblindfull** [comment]
Thank for your reply. Indeed, it's forge 35.1.1 ! Sorry for my mistake.

The log I provide to you is the only part that concern your mod. It provide all the infos you need. The full lastestlog is very long and aren't related to your mod activity apart this one.

Have a good day

**Comment by solarblindfull** [comment]
The last version of your mod (moreboots - 1.3.1) crash the same way as well as you cas see in this much detailed log

<details>
<summary>Lastest server log part1</summary>

[14déc.2020 19:37:29.292] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: net.minecraft.block.SkullBlock.func_196292_N_()Lnet/minecraft/block/SkullBlock$ISkullType;

	Index: 3

	Listeners:

		0: NORMAL

		1: ASM: class com.northwestwind.moreboots.init.TileEntityInit registerTileEntity(Lnet/minecraftforge/event/RegistryEvent$Register;)V

		2: ASM: class com.northwestwind.moreboots.init.ItemInit registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V

		3: ASM: class com.northwestwind.moreboots.init.BlockInit registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V

		4: ASM: class com.northwestwind.moreboots.init.BlockInit registerBlockItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V

java.lang.NoSuchMethodError: net.minecraft.block.SkullBlock.func_196292_N_()Lnet/minecraft/block/SkullBlock$ISkullType;

	at com.northwestwind.moreboots.init.block.vanilla.VanishingSkullBlock.<init>(VanishingSkullBlock.java:18)

	at com.northwestwind.moreboots.init.BlockInit.registerBlocks(BlockInit.java:88)

	at net.minecraftforge.eventbus.ASMEventHandler_220_BlockInit_registerBlocks_Register.invoke(.dynamic)

	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)

	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)

	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)

	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)

	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)

	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56)

	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40)

	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243)

	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230)

	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196)

	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44)

	at net.minecraft.server.Main.main(Main.java:95)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)

	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)

	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)

	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)

	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)

	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

[14déc.2020 19:37:29.295] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:block> dispatch for modid moreboots

java.lang.NoSuchMethodError: net.minecraft.block.SkullBlock.func_196292_N_()Lnet/minecraft/block/SkullBlock$ISkullType;

	at com.northwestwind.moreboots.init.block.vanilla.VanishingSkullBlock.<init>(VanishingSkullBlock.java:18) ~[moreboots:1.3.1-1.16.x]

	at com.northwestwind.moreboots.init.BlockInit.registerBlocks(BlockInit.java:88) ~[moreboots:1.3.1-1.16.x]

	at net.minecraftforge.eventbus.ASMEventHandler_220_BlockInit_registerBlocks_Register.invoke(.dynamic) ~[?:?]

	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]

	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]

	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1]

	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?]

	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_202]

	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?]

	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?]

	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[forge:?]

	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?]

	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?]

	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]

	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]

	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.1.jar:35.1]

	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]

	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.1.jar:?]

	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.1.jar:?]

	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.1.jar:?]

</details>

<details>
<summary>Lastest server log part2</summary>
[14déc.2020 19:37:38.572] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [

	More Boots (moreboots) encountered an error during the load_registries event phase

java.lang.NoSuchMethodError: net.minecraft.block.SkullBlock.func_196292_N_()Lnet/minecraft/block/SkullBlock$ISkullType;

]

	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?]

	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?]

	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?]

	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?]

	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]

	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.1.jar:35.1]

	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]

	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]

	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.1.jar:?]

	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.1.jar:?]

	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.1.jar:?]
</details>

**Comment by North-West-Wind** [comment]
(Hopefully) This should be fixed on the latest update (1.4.1)
I'm closing this now.
